import type { AssetFoundry } from '../foundry/foundry.js';
import { classifyFailure, isFallbackEligible } from './classify-failure.js';
import type { AssetGenerationGateway, AssetGenerationOutcome, AssetGenerationRequest } from './types.js';

/**
 * Wraps AssetFoundry.fulfill() behind the same AssetGenerationGateway contract the legacy path
 * implements. AssetPipeline never builds a Foundry AssetRequest or touches AssetFoundry directly —
 * this is the one place that translation happens (production standard: "the production pipeline
 * must not directly know about individual external providers").
 *
 * Foundry's own compile step (SpriteCompiler, packages/assets/src/foundry/compilers.ts) uses the
 * same PixelArtProcessor/knockoutVfxBackground primitives and the same canonical frame sizes
 * (FOUNDRY_CANONICAL_FRAME) as AssetPipeline's existing compileActorFrame — verified equivalent,
 * not just assumed. Even so, this gateway's result still flows through AssetPipeline's existing
 * deterministic-checks + VLM critique pipeline afterward, exactly as legacy-generated bytes do;
 * Foundry's own qaScore/qaPassed/license/provenance are captured here for observability and
 * provenance (see AssetGenerationDiagnostics) rather than silently replacing MetroForge's existing
 * maturity gate. That is a deliberate, conservative choice for this integration pass, not an
 * oversight — see the migration report for the reasoning.
 */
export class FoundryAssetGenerationGateway implements AssetGenerationGateway {
  readonly backend = 'foundry' as const;

  constructor(private readonly foundry: AssetFoundry) {}

  async generate(request: AssetGenerationRequest): Promise<AssetGenerationOutcome> {
    if (request.localStyleAdapter !== undefined)
      return { ok: false, backend: this.backend, failureClass: 'unsupported-capability', message: 'Foundry does not support local style adapters', fallbackEligible: true };
    try {
      const result = await this.foundry.fulfill({
        id: request.id,
        assetType: request.assetType,
        prompt: request.prompt,
        negativePrompt: request.negativePrompt,
        style: {
          visualStyle: request.visualStyle,
          palette: request.palette,
          pixelArt: request.pixelArt,
        },
        dimensions: { width: request.width, height: request.height },
        output: {
          engine: 'godot',
          transparentBackground: request.transparentBackground,
        },
        constraints: {
          commercialUseRequired: request.commercialUseRequired,
          freeOnly: request.freeOnly,
          localOnly: request.localOnly,
        },
        consistency: {},
        seed: request.seed,
        maxRetries: request.maxRetries,
      });

      return {
        ok: true,
        backend: this.backend,
        buffer: result.buffer,
        provider: result.provider,
        modelId: result.modelId,
        // Foundry's own QA verdict — `placeholder` is true for both "fell back" and "failed QA",
        // which is the right conservative signal here: neither case should read as qaPassed=true.
        qaPassed: !result.placeholder,
        qaScore: result.qaScore,
        license: {
          commercialUse: result.provenance.commercialUse,
          status: result.provenance.licenseStatus,
          reason: result.provenance.license,
        },
        provenance: result.provenance as unknown as Record<string, unknown>,
        transformations: result.provenance.transformations,
        fallbackDepth: result.fallbackDepth,
        fallbackReason: result.fallbackReason,
        cacheHit: result.cacheHit,
      };
    } catch (err) {
      const failureClass = classifyFailure(err);
      return {
        ok: false,
        backend: this.backend,
        failureClass,
        message: err instanceof Error ? err.message : String(err),
        fallbackEligible: isFallbackEligible(failureClass),
      };
    }
  }
}
