import {it,expect} from 'vitest';
import {mkdtempSync,mkdirSync,readFileSync,writeFileSync} from 'node:fs';
import {join,dirname} from 'node:path';
import {tmpdir} from 'node:os';
import {GameDNASchema} from '@metroforge/schemas';
import {generateGameContent} from '@metroforge/procedural';
import {GodotProjectAssembler} from '@metroforge/godot';
import {regenerateRoom} from './project-edit-service.js';

it('keeps archive edits and explicit removal in full regeneration; explicit encounter regeneration restores its guard',()=>{
  const root=mkdtempSync(join(tmpdir(),'archive-regenerate-'));
  const dna=GameDNASchema.parse({version:'1',identity:{title:'Stormglass Reliquary',genre:'Metroidvania',tone:'quiet danger',visualStyle:'original gothic pixel art'},technical:{resolution:{width:1920,height:1080},tileSize:32,targetPlaytimeHours:2,difficulty:'normal'},combat:{style:'sword',meleeEnabled:true,rangedEnabled:false},movement:{walkSpeed:220,runSpeed:380,jumpHeight:160,gravity:980},abilities:['dash','double_jump','wall_slide','wall_jump','ground_slam','air_dash'].map(id=>({id,name:id,category:'movement',enabled:true})),world:{biomeCount:1,roomCount:48},narrative:{premise:'Recover the weather seals',protagonist:'Courier',centralConflict:'Restore the castle'},seed:42,profile:'MEDIUM',archetype:'SIDE_VIEW_METROIDVANIA'});
  const graph=JSON.parse(readFileSync('templates/godot-metroidvania/data/visual/blueprints/stormglass-archive-wing-campaign-v1.json','utf8')).worldGraph;
  const ids=graph.nodes.map((n:{id:string})=>n.id);
  const content=generateGameContent(dna,'MEDIUM',42,'room_038',ids);
  const write=(path:string,data:unknown)=>{mkdirSync(dirname(join(root,path)),{recursive:true});writeFileSync(join(root,path),JSON.stringify(data));};
  write('game_dna.json',dna);write('world_graph.json',graph);writeFileSync(join(root,'project.godot'),'config_version=5\n');
  for(const key of ['enemies','bosses','items','npcs'] as const)write('data/'+key+'/'+key+'.json',{[key]:content[key]});
  expect(new GodotProjectAssembler().recompileRooms({outputDir:root,gameDna:dna,worldGraph:graph,gameContent:content,roomIds:ids,targetRoomIds:['room_046','room_047']}).errors).toEqual([]);
  const file=join(root,'data/rooms/rooms.json'),read=()=>JSON.parse(readFileSync(file,'utf8'));
  const edited=read(),room=edited.rooms.room_047;
  room.entityPlacements.find((p:{kind:string})=>p.kind==='enemy').x=1232;
  room.entityPlacements.find((p:{kind:string})=>p.kind==='item_pickup').x=1320;
  writeFileSync(file,JSON.stringify(edited));
  const sibling=JSON.stringify(edited.rooms.room_046);
  expect(regenerateRoom(root,'room_047','full').success).toBe(true);
  expect(read().rooms.room_047.entityPlacements).toEqual(room.entityPlacements);
  expect(JSON.stringify(read().rooms.room_046)).toBe(sibling);
  const removed=read();removed.rooms.room_047.forceEnemy=false;
  removed.rooms.room_047.entityPlacements=removed.rooms.room_047.entityPlacements.filter((p:{kind:string})=>p.kind!=='enemy');
  removed.rooms.room_047.enemies=[];writeFileSync(file,JSON.stringify(removed));
  expect(regenerateRoom(root,'room_047','full').success).toBe(true);
  expect(read().rooms.room_047.enemies).toEqual([]);expect(read().rooms.room_047.forceEnemy).toBe(false);
  expect(regenerateRoom(root,'room_047','encounter').success).toBe(true);
  const restored=read().rooms.room_047;
  expect(restored.forceEnemy).toBeUndefined();
  expect(restored.enemies).toEqual(['room_047_reward_guard']);
  expect(restored.entityPlacements.find((p:{kind:string})=>p.kind==='enemy').x).toBe(1088);
  expect(restored.entityPlacements.find((p:{kind:string})=>p.kind==='item_pickup').x).toBe(1320);
});
