import {describe,it,expect} from 'vitest';
import {GameDNASchema} from '@metroforge/schemas';
import {selectAuthoredWorld} from './world-layout.js';
const dna=GameDNASchema.parse({version:'1',identity:{title:'Stormglass Reliquary',genre:'Metroidvania',tone:'quiet danger',visualStyle:'original gothic pixel art'},technical:{resolution:{width:1920,height:1080},tileSize:32,targetPlaytimeHours:2,difficulty:'normal'},combat:{style:'sword',meleeEnabled:true,rangedEnabled:false},movement:{walkSpeed:220,runSpeed:380,jumpHeight:160,gravity:980},abilities:['dash','double_jump','wall_slide','wall_jump','ground_slam','air_dash'].map(id=>({id,name:id,category:'movement',enabled:true})),world:{biomeCount:1,roomCount:48},narrative:{premise:'Recover the original weather seals',protagonist:'Courier',centralConflict:'Restore the castle'},seed:42,profile:'MEDIUM',archetype:'SIDE_VIEW_METROIDVANIA'});
describe('Explicit Stormglass plans across native engine generation',()=>{
 it.each(['godot','unity','unreal'])('retains all plan sizes, progression and architecture for %s',targetEngine=>{for(const [worldLayout,rooms]of [['stormglass-gallery',43],['stormglass-expanded-region',46],['stormglass-archive-wing',48]] as const){const actual=selectAuthoredWorld(dna,{worldLayout,targetEngine,seed:42})!,godot=selectAuthoredWorld(dna,{worldLayout,targetEngine:'godot',seed:42})!;expect(actual.roomIds).toHaveLength(rooms);expect(actual).toEqual(godot);expect(actual.bossRoomIds).toEqual(['room_008','room_018','room_028','room_038']);expect(actual.worldGraph.nodes.find(n=>n.id==='room_043')?.metadata.targetTileHeight).toBe(worldLayout==='stormglass-gallery'?undefined:96);}});
 it('rejects unknown engines, genre conflicts and topology overrides without silently replacing a plan',()=>{expect(()=>selectAuthoredWorld(dna,{worldLayout:'stormglass-archive-wing',targetEngine:'unknown',seed:42})).toThrow('Unknown target engine');expect(()=>selectAuthoredWorld({...dna,archetype:'TOP_DOWN_ACTION_ADVENTURE'},{worldLayout:'stormglass-archive-wing',targetEngine:'unity',seed:42})).toThrow('requires side-view');expect(()=>selectAuthoredWorld(dna,{worldLayout:'stormglass-archive-wing',targetEngine:'unity',seed:42,worldOverride:{roomCount:40}})).toThrow('48 authored rooms');});
 it('keeps procedural requests independent of authored campaign recipes',()=>{expect(selectAuthoredWorld(dna,{worldLayout:'procedural',targetEngine:'unity',seed:42})).toBeNull();});
});
