extends SceneTree
const Grid = preload("res://scripts/MicrocellGrid.gd")
const Shots = preload("res://scripts/InstrumentSimulation.gd")
const Program = preload("res://scripts/InstrumentProgram.gd")
const State = preload("res://scripts/RunState.gd")
var passed: int = 0
var failed: int = 0
var results: Array = []

func _initialize() -> void:
	call_deferred("run_tests")

func check(value: bool, label: String) -> void:
	passed += int(value)
	failed += int(not value)
	results.append({"test":label,"passed":value})
	print(("PASS " if value else "FAIL ")+label)

func recipe(operator: String, state: String = "dark_energy") -> Dictionary:
	return {"waveform":"photon","operator":operator,"state":state,"trigger":"impact"}

func grid_world():
	return Grid.new(220,80,77)

func shoot(shots, instrument: String = "photon", direction: Vector2 = Vector2.RIGHT) -> Dictionary:
	var fired: Dictionary = shots.fire(instrument,Vector2(40,100),direction)
	for index in 48: shots.step()
	return fired

func run_tests() -> void:
	for instrument in Program.DEFAULTS:
		var compiled: Dictionary = Program.compile(Program.DEFAULTS[instrument])
		var stats: Dictionary = compiled.definition.duplicate()
		stats.erase("recipe")
		check(stats == Shots.DEFINITIONS[instrument],"original "+instrument+" preview preserves every verified firing statistic")
	check(not Program.compile({}).accepted,"incomplete module sets are rejected")
	var unknown: Dictionary = recipe("collapse")
	unknown.extra = true
	check(not Program.compile(unknown).accepted,"unknown program fields cannot be silently ignored")
	check(not Program.compile(recipe("tunneling")).accepted,"Tunneling is locked until its blueprint is discovered")
	check(not Program.compile(recipe("entanglement")).accepted,"Entanglement is locked until its blueprint is discovered")
	check(not Program.compile(recipe("superposition"),["entanglement","tunneling"]).accepted,"incompatible Superposition modules explain a rejected preview")
	var shots = Shots.new(grid_world())
	var before: PackedByteArray = var_to_bytes(shots.programs)
	check(not shots.set_program("photon",recipe("tunneling")).accepted and var_to_bytes(shots.programs) == before and shots.energy == 100.0,"locked application leaves loadouts and resources unchanged")
	check(shots.set_program("photon",recipe("tunneling"),["tunneling"]).accepted and shots.energy == 100.0,"unlocked application changes behavior without free energy or stat grants")
	var fired: Dictionary = shots.fire("photon",Vector2(40,100),Vector2.RIGHT)
	check(fired.accepted and shots.energy == 93.0 and shots.slot_count() == 1,"Tunneling preview's seven-energy price is charged by real firing")
	shots.set_program("photon",Program.DEFAULTS.photon)
	for index in 6: shots.step()
	check(shots.projectiles[0].program.recipe.operator == "tunneling","a pending custom shot retains its compiled program after reconfiguration")
	var wall = grid_world()
	for x in range(14,22): wall.set_material(x,25,Grid.CellMaterial.SOLID)
	var tunnel = Shots.new(wall)
	tunnel.set_program("photon",recipe("tunneling"),["tunneling"])
	tunnel.add_target(1,Rect2(96,96,8,8),100.0)
	shoot(tunnel)
	check(is_equal_approx(tunnel.targets[1].hp,90.4),"eight actual occupied cells attenuate the target hit once to 9.6 damage")
	check(wall.heat[25*wall.width+14] == 0.0,"Dark energy traversal does not secretly heat the wall")
	var thick = grid_world()
	for x in range(14,47): thick.set_material(x,25,Grid.CellMaterial.SOLID)
	var stopped = Shots.new(thick)
	stopped.set_program("photon",recipe("tunneling"),["tunneling"])
	stopped.add_target(1,Rect2(196,96,8,8),100.0)
	shoot(stopped)
	check(stopped.targets[1].hp == 100.0 and stopped.projectiles.is_empty(),"a 33rd occupied cell stops Tunneling before the target")
	var protected = grid_world()
	protected.set_material(14,25,Grid.CellMaterial.SOLID,true)
	var safe = Shots.new(protected)
	safe.set_program("photon",recipe("tunneling","thermal"),["tunneling"])
	safe.add_target(1,Rect2(80,96,8,8),100.0)
	shoot(safe)
	check(safe.targets[1].hp == 100.0 and protected.heat[25*protected.width+14] == 0.0,"protected station material always blocks Tunneling and rejects its heat")
	var heat_grid = grid_world()
	heat_grid.set_material(14,25,Grid.CellMaterial.SOLID)
	var thermal = Shots.new(heat_grid)
	thermal.set_program("photon",recipe("tunneling","thermal"),["tunneling"])
	shoot(thermal)
	check(heat_grid.heat[25*heat_grid.width+14] == 0.95,"Thermal module has a real material effect separate from Dark energy")
	var split_grid = grid_world()
	for x in range(13,40): split_grid.set_material(x,25,Grid.CellMaterial.FLUID)
	var split = Shots.new(split_grid)
	var combined: Dictionary = Program.DEFAULTS.tachyon.duplicate(true)
	split.set_program("photon",combined)
	var split_fired: Dictionary = split.fire("photon",Vector2(40,100),Vector2.RIGHT)
	check(split_fired.accepted and split_fired.windup == 9 and split.slot_count() == 3 and split.energy == 94.0,"edited waveform changes telegraph, price and reserved capacity in the selected slot")
	for index in 9: split.step()
	check(split.projectiles.size() == 3 and split.projectiles.all(func(shot): return shot.split_child),"edited Superposition performs exactly one three-child split")
	var full = Shots.new(grid_world())
	full.set_program("photon",combined)
	full.external_slots = 62
	var rejected: Dictionary = full.fire("photon",Vector2(40,100),Vector2.RIGHT)
	check(not rejected.accepted and rejected.reason == "capacity" and full.energy == 100.0 and full.next_id == 1,"custom split admission respects hostile capacity without charging rejected shots")
	var linked = Shots.new(grid_world())
	for id in range(1,19): linked.add_target(id,Rect2(60+id*12,96,8,8),100.0,true)
	linked.add_target(100,Rect2(360,96,8,8),100.0)
	check(not linked.link_targets(1,100).accepted,"objective crystals cannot be substituted for living entanglement targets")
	check(not linked.link_targets(1,1).accepted and linked.energy == 100.0,"self-links reject without charging energy")
	check(linked.link_targets(1,2).accepted,"two distinct living targets form a bounded link")
	check(not linked.link_targets(1,3).accepted and linked.links.size() == 1,"one target cannot join a second link")
	shoot(linked)
	check(linked.targets[1].hp == 88.0 and linked.targets[2].hp == 94.0,"one direct hit transfers exactly half damage once with no recursive echo")
	for pair in range(1,8): linked.link_targets(pair*2+1,pair*2+2)
	check(linked.links.size() == 8 and not linked.link_targets(17,18).accepted,"eight links cap further requests without replacing a pair")
	linked.targets[1].hp = 0.0
	linked.step()
	check(linked.links.size() == 7,"a target death immediately clears its entanglement link")
	for index in 360: linked.step()
	check(linked.links.is_empty(),"all links expire at the six-second fixed-tick boundary")
	var tagging = Shots.new(grid_world())
	tagging.set_program("photon",recipe("entanglement"),["entanglement"])
	tagging.add_target(1,Rect2(72,96,8,8),100.0,true)
	tagging.add_target(2,Rect2(72,126,8,8),100.0,true)
	shoot(tagging)
	check(tagging.link_marks.has("photon") and tagging.energy < 100.0,"an actual Entanglement hit marks its first living target")
	shoot(tagging,"photon",Vector2(36,30))
	check(tagging.links.size() == 1 and tagging.link_marks.is_empty(),"a second aimed hit forms the link through projectile gameplay")
	check(not State.build(State.snapshot({"instruments":tagging}),{}).accepted,"v1 compact saves reject programmable state instead of silently discarding loadouts and links")
	print("QUANTUM_PROGRAMMING_RESULTS "+JSON.stringify({"passed":passed,"failed":failed,"results":results}))
	quit(0 if failed == 0 else 1)
