import {describe,it,expect} from 'vitest';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {GameDNASchema} from '@metroforge/schemas';
import {buildStormglassGalleryBlueprint} from '../../godot/src/stormglass-gallery-blueprint.js';
import {buildGameplayPack} from './gameplay-pack.js';
const dna=GameDNASchema.parse({version:'0.1.0',archetype:'SIDE_VIEW_METROIDVANIA',identity:{title:'Stormglass Reliquary',genre:'Metroidvania',tone:'dark',visualStyle:'pixel art'},technical:{resolution:{width:1920,height:1080},tileSize:32,targetPlaytimeHours:1,difficulty:'normal'},combat:{style:'melee',meleeEnabled:true,rangedEnabled:false},movement:{walkSpeed:220,runSpeed:380,jumpHeight:160,gravity:980},abilities:[{id:'dash',name:'Dash',category:'movement',enabled:true}],world:{biomeCount:1,roomCount:48},narrative:{premise:'Archive',protagonist:'Courier',centralConflict:'Return'},seed:42,profile:'MEDIUM'});
function pack(profile:'gallery'|'expanded-region'|'archive-wing', middleGate=false) {
 const plan=buildStormglassGalleryBlueprint(profile),roomIds=plan.rooms.map(r=>r.id);
 return buildGameplayPack({outputDir:join(tmpdir(),'spatial-export-'+profile),gameDna:dna,roomIds,worldGraph:{version:'0.1.0',seed:42,regions:[],nodes:plan.rooms.map(r=>({id:r.id,type:'room',label:r.name,metadata:{archetype:r.theme==='rest'?'save':r.theme==='stairwell'?'traversal':'combat',stormglassRoomTheme:r.theme,stormglassRegionProfile:profile,stormglassCampaignLayout:'stormglass-gallery-campaign-v1',targetTileWidth:r.width/32,targetTileHeight:r.height/32}})),edges:plan.links.map((l,i)=>({id:'edge_'+i,from:l.from,to:l.to,transition:l.direction,requirements:middleGate&&l.from==='room_043'&&l.to==='room_044'?['dash']:l.requirements,optional:l.optional,bidirectional:true}))},progressionGraph:{version:'0.1.0',seed:42,startNodeId:roomIds[0]!,endNodeId:roomIds.at(-1)!,nodes:[],edges:[],abilities:[],criticalPath:roomIds},textureFiles:new Map([['assets/tilesets/biome_0/source.png',Buffer.from('presence')]])});
}
describe('native authored stair flight export',()=>{
 it('exports the continuous 192px stair rises instead of isolated unreachable ledges',()=>{const room=pack('archive-wing').rooms.find(r=>r.id==='room_005')!;expect(room.stairFlights?.[0]).toEqual({from:{x:144,y:3008},to:{x:864,y:2816},thickness:32,oneWay:true});expect(room.stairFlights!.length).toBeGreaterThan(10);for(let i=1;i<room.stairFlights!.length;i++)expect(room.stairFlights![i]!.from.y).toBe(room.stairFlights![i-1]!.to.y);expect(room.doors.find(d=>d.targetRoomId==='room_004')?.x).toBe(48);expect(room.solids.find(r=>r.name==='Platform_15')?.oneWay).toBe(true);expect(room.solids.filter(r=>r.name?.startsWith('Floor')).every(r=>!r.oneWay)).toBe(true);});
 it('preserves the earlier gallery solid-flight collision policy',()=>{const room=pack('gallery').rooms.find(r=>r.id==='room_005')!;expect(room.stairFlights?.length).toBeGreaterThan(0);expect(room.stairFlights!.every(f=>f.oneWay===false)).toBe(true);expect(room.solids.filter(r=>r.name?.startsWith('Platform_')).every(r=>!r.oneWay)).toBe(true);});
 it('exports archive chamber return slopes and leaves ordinary rooms without invented flights',()=>{const rooms=pack('archive-wing').rooms;expect(rooms.find(r=>r.id==='room_047')?.stairFlights?.length).toBeGreaterThan(0);expect(rooms.find(r=>r.id==='room_003')?.stairFlights).toBeUndefined();});
});
